theme = "gruvbox_dark_hard"

[editor]
line-number = "relative"
mouse = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

#BQN keymappings
[keys.insert."\\"]
"=" = [ ":insert-output /bin/echo -n Ã—", "move_char_right" ]
minus = [ ":insert-output /bin/echo -n Ã·", "move_char_right" ]
"+" = [ ":insert-output /bin/echo -n â‹†", "move_char_right" ]
"_" = [ ":insert-output /bin/echo -n âˆš", "move_char_right" ]
"b" = [ ":insert-output /bin/echo -n âŒŠ", "move_char_right" ]
"B" = [ ":insert-output /bin/echo -n âŒˆ", "move_char_right" ]
"t" = [ ":insert-output /bin/echo -n âˆ§", "move_char_right" ]
"v" = [ ":insert-output /bin/echo -n âˆ¨", "move_char_right" ]
"~" = [ ":insert-output /bin/echo -n Â¬", "move_char_right" ]
"<" = [ ":insert-output /bin/echo -n â‰¤", "move_char_right" ]
">" = [ ":insert-output /bin/echo -n â‰¥", "move_char_right" ]
"/" = [ ":insert-output /bin/echo -n â‰ ", "move_char_right" ]
"m" = [ ":insert-output /bin/echo -n â‰¡", "move_char_right" ]
"M" = [ ":insert-output /bin/echo -n â‰¢", "move_char_right" ]
"{" = [ ":insert-output /bin/echo -n âŠ£", "move_char_right" ]
"}" = [ ":insert-output /bin/echo -n âŠ¢", "move_char_right" ]
"z" = [ ":insert-output /bin/echo -n â¥Š", "move_char_right" ]
"," = [ ":insert-output /bin/echo -n âˆ¾", "move_char_right" ]
"." = [ ":insert-output /bin/echo -n â‰", "move_char_right" ]
"Z" = [ ":insert-output /bin/echo -n â‹ˆ", "move_char_right" ]
"r" = [ ":insert-output /bin/echo -n â†‘", "move_char_right" ]
"c" = [ ":insert-output /bin/echo -n â†“", "move_char_right" ]
"d" = [ ":insert-output /bin/echo -n â†•", "move_char_right" ]
"H" = [ ":insert-output /bin/echo -n Â«", "move_char_right" ]
"L" = [ ":insert-output /bin/echo -n Â»", "move_char_right" ]
"q" = [ ":insert-output /bin/echo -n âŒ½", "move_char_right" ]
"a" = [ ":insert-output /bin/echo -n â‰", "move_char_right" ]
"T" = [ ":insert-output /bin/echo -n â‹", "move_char_right" ]
"V" = [ ":insert-output /bin/echo -n â’", "move_char_right" ]
"i" = [ ":insert-output /bin/echo -n âŠ", "move_char_right" ]
"I" = [ ":insert-output /bin/echo -n âŠ‘", "move_char_right" ]
"o" = [ ":insert-output /bin/echo -n âŠ", "move_char_right" ]
"O" = [ ":insert-output /bin/echo -n âŠ’", "move_char_right" ]
"e" = [ ":insert-output /bin/echo -n âˆŠ", "move_char_right" ]
"E" = [ ":insert-output /bin/echo -n â·", "move_char_right" ]
"u" = [ ":insert-output /bin/echo -n âŠ”", "move_char_right" ]
"(" = [ ":insert-output /bin/echo -n âŸ¨", "move_char_right" ]
"0" = [ ":insert-output /bin/echo -n â€¢", "move_char_right" ]
")" = [ ":insert-output /bin/echo -n âŸ©", "move_char_right" ]
"[" = [ ":insert-output /bin/echo -n â†", "move_char_right" ]
";" = [ ":insert-output /bin/echo -n â‹„", "move_char_right" ]
":" = [ ":insert-output /bin/echo -n Â·", "move_char_right" ]
"'" = [ ":insert-output /bin/echo -n â†©", "move_char_right" ]
"?" = [ ":insert-output /bin/echo -n â‡", "move_char_right" ]
space = [ ":insert-output /bin/echo -n â€¿", "move_char_right" ]
"9" = [ ":insert-output /bin/echo -n Â¯", "move_char_right" ]
"8" = [ ":insert-output /bin/echo -n âˆ", "move_char_right" ]
"p" = [ ":insert-output /bin/echo -n Ï€", "move_char_right" ]
# 1-Modifier
"\"" = [ ":insert-output /bin/echo -n Ë™", "move_char_right" ]
"`" = [ ":insert-output /bin/echo -n Ëœ", "move_char_right" ]
"1" = [ ":insert-output /bin/echo -n Ë˜", "move_char_right" ]
"2" = [ ":insert-output /bin/echo -n Â¨", "move_char_right" ]
"4" = [ ":insert-output /bin/echo -n âŒœ", "move_char_right" ]
"3" = [ ":insert-output /bin/echo -n â¼", "move_char_right" ]
"5" = [ ":insert-output /bin/echo -n Â´", "move_char_right" ]
"6" = [ ":insert-output /bin/echo -n Ë", "move_char_right" ]
# 2-Modifier
"j" = [ ":insert-output /bin/echo -n âˆ˜", "move_char_right" ]
"k" = [ ":insert-output /bin/echo -n â—‹", "move_char_right" ]
"h" = [ ":insert-output /bin/echo -n âŠ¸", "move_char_right" ]
"l" = [ ":insert-output /bin/echo -n âŸœ", "move_char_right" ]
"K" = [ ":insert-output /bin/echo -n âŒ¾", "move_char_right" ]
"%" = [ ":insert-output /bin/echo -n âŠ˜", "move_char_right" ]
"$" = [ ":insert-output /bin/echo -n â—¶", "move_char_right" ]
"^" = [ ":insert-output /bin/echo -n âŠ", "move_char_right" ]
"!" = [ ":insert-output /bin/echo -n â‰", "move_char_right" ]
"@" = [ ":insert-output /bin/echo -n âš‡", "move_char_right" ]
"#" = [ ":insert-output /bin/echo -n âŸ", "move_char_right" ]
# about block
"w" = [ ":insert-output /bin/echo -n ğ•¨", "move_char_right" ]
"W" = [ ":insert-output /bin/echo -n ğ•", "move_char_right" ]
"s" = [ ":insert-output /bin/echo -n ğ•¤", "move_char_right" ]
"S" = [ ":insert-output /bin/echo -n ğ•Š", "move_char_right" ]
"x" = [ ":insert-output /bin/echo -n ğ•©", "move_char_right" ]
"X" = [ ":insert-output /bin/echo -n ğ•", "move_char_right" ]
"f" = [ ":insert-output /bin/echo -n ğ•—", "move_char_right" ]
"F" = [ ":insert-output /bin/echo -n ğ”½", "move_char_right" ]
"g" = [ ":insert-output /bin/echo -n ğ•˜", "move_char_right" ]
"G" = [ ":insert-output /bin/echo -n ğ”¾", "move_char_right" ]
"R" = [ ":insert-output /bin/echo -n ğ•£", "move_char_right" ]
